#macro Uprr TempUpgrade
#macro Uprl UpgradeExecute
#macro Uprf UpgradeExplode
#macro Upri UpgradeShatter
#macro Uprer UpgradeGrowth
#macro Upren UpgradeGravitational
#macro Upra TempUpgrade
#macro Upll UpgradeStrike
#macro Uplf TempUpgrade
#macro Upli TempUpgrade
#macro Upler TempUpgrade
#macro Uplen TempUpgrade
#macro Upla TempUpgrade
#macro Upff TempUpgrade
#macro Upfi TempUpgrade
#macro Upfer TempUpgrade
#macro Upfen TempUpgrade
#macro Upfa TempUpgrade
#macro Upii TempUpgrade
#macro Upier TempUpgrade
#macro Upien TempUpgrade
#macro Upia TempUpgrade
#macro Uperer TempUpgrade
#macro Uperen TempUpgrade
#macro Upera TempUpgrade
#macro Upenen TempUpgrade
#macro Upena TempUpgrade
#macro Upaa TempUpgrade
